name: Docker Workflow
on: [push]

jobs:
  k6_local_test:
    name: k6 run in docker
    runs-on: ubuntu-latest
    container: grafana/k6:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Create Result folder
        run: mkdir ~/Result

      - name: Local k6 test
        run: k6 run GetUserTest.js
