name: Docker Workflow
on: [push]
      
jobs:
  k6_local_test:
    name: k6 run in docker
    runs-on: ubuntu-latest
    container: grafana/k6:latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: create Result
        run: apt update && apt install sudo && sudo mkdir Result      
        
      - name: Local k6 test
        run: k6 run GetUserTest.js
