name: Docker Workflow
on: [push]
      
jobs:
  k6_local_test:
    name: k6 run in docker
    runs-on: ubuntu-latest
    container: grafana/k6:latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install k6
        run: |
          apk update
          apk add --no-cache sudo
          sudo apk add --no-cache k6
        
      - name: create Result
        run: apk update && apk install sudo && mkdir Result      
        
      - name: Local k6 test
        run: k6 run GetUserTest.js
